# Generated by Django 5.1.3 on 2024-12-08 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountrySelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(choices=[('Nigeria', 'Nigeria'), ('United States', 'United States'), ('United Kingdom', 'United Kingdom'), ('Canada', 'Canada'), ('Eritrea', 'Eritrea'), ('Germany', 'Germany'), ('France', 'France'), ('Australia', 'Australia'), ('Japan', 'Japan'), ('South Korea', 'South Korea'), ('South Africa', 'South Africa'), ('Brazil', 'Brazil'), ('Italy', 'Italy'), ('Singapore', 'Singapore'), ('Switzerland', 'Switzerland'), ('New Zealand', 'New Zealand'), ('Mexico', 'Mexico'), ('Russia', 'Russia'), ('Turkey', 'Turkey'), ('Malaysia', 'Malaysia'), ('Saudi Arabia', 'Saudi Arabia'), ('Belgium', 'Belgium')], max_length=255)),
                ('guest_id', models.CharField(max_length=255)),
            ],
        ),
    ]
