# Generated by Django 5.1.2 on 2024-11-14 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountrySelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(choices=[('Nigeria', 'Nigeria'), ('United States', 'United States'), ('United Kingdom', 'United Kingdom'), ('Canada', 'Canada'), ('Eritrea', 'Eritrea')], max_length=255)),
                ('guest_id', models.CharField(max_length=255)),
            ],
        ),
    ]
