# Generated by Django 5.1.2 on 2024-11-14 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Countries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countryselection',
            name='country',
            field=models.CharField(choices=[('Nigeria', 'Nigeria'), ('United States', 'United States'), ('United Kingdom', 'United Kingdom'), ('Canada', 'Canada'), ('Eritrea', 'Eritrea'), ('Germany', 'Germany'), ('France', 'France'), ('Australia', 'Australia'), ('Japan', 'Japan'), ('South Korea', 'South Korea'), ('South Africa', 'South Africa'), ('Brazil', 'Brazil'), ('Italy', 'Italy'), ('Singapore', 'Singapore'), ('Switzerland', 'Switzerland'), ('New Zealand', 'New Zealand'), ('Mexico', 'Mexico'), ('Russia', 'Russia'), ('Turkey', 'Turkey'), ('Malaysia', 'Malaysia'), ('Saudi Arabia', 'Saudi Arabia'), ('Belgium', 'Belgium')], max_length=255),
        ),
    ]
