# Generated by Django 5.1.3 on 2024-12-16 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OrderAndShipment', '0002_paystackinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paystackinfo',
            old_name='transaction_reference',
            new_name='transactionReference',
        ),
    ]
