# Generated by Django 5.1.3 on 2024-12-18 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderAndShipment', '0004_transaction_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
        migrations.AlterField(
            model_name='rating',
            name='message',
            field=models.CharField(max_length=255),
        ),
    ]
