# Generated by Django 5.1.3 on 2024-12-19 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderAndShipment', '0006_shipping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipping',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='shipping',
            name='last_name',
        ),
        migrations.AddField(
            model_name='shipping',
            name='full_name',
            field=models.CharField(default='1', max_length=40),
        ),
    ]
