# Generated by Django 5.1.3 on 2024-12-19 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderAndShipment', '0007_remove_shipping_first_name_remove_shipping_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='dispatchRiderFullName',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='dispatchRiderPhone',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
