# Generated by Django 5.1.2 on 2024-11-24 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogPost', '0002_blogpostimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='photo',
            field=models.ImageField(default='', upload_to='blog_images'),
        ),
        migrations.AlterField(
            model_name='blogpostimage',
            name='image',
            field=models.ImageField(upload_to='blog_images'),
        ),
    ]
