# Generated by Django 5.1.2 on 2024-11-24 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogPost', '0003_blogpost_photo_alter_blogpostimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='introduction',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
