# Generated by Django 5.1.2 on 2024-11-14 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='ProductImages')),
                ('size', models.CharField(blank=True, max_length=20, null=True)),
                ('promo_price', models.DecimalField(decimal_places=2, default='1', max_digits=12)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('warranty', models.CharField(blank=True, max_length=60, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('category', models.CharField(blank=True, max_length=20, null=True)),
                ('productCategoryIdentifier', models.CharField(blank=True, max_length=20, null=True)),
                ('subcategory', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
