# Generated by Django 5.1.3 on 2024-12-08 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_items_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='weight',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
